'use client';
import {useCallback,useEffect,useState} from 'react';
import {Wifi,Utensils,Hotel,ClipboardList,Clock,Phone} from '@/components/Icons';
type Service={id:string;name:string;description:string|null;price:string|null;estimatedMinutes:number};
type Menu={id:string;name:string;description:string|null;price:string;category:{name:string}|null};
type Data={hotel:{name:string;address:string|null;phone:string|null;info:{wifiName:string|null;wifiPassword:string|null;breakfastTime:string|null;checkinTime:string|null;checkoutTime:string|null;policies:string|null;facilities:string|null}|null};room:{id:string;number:string};services:Service[];menu:Menu[]};
type GuestRequest={id:string;status:string;quantity:number;note:string|null;createdAt:string;service:{name:string};feedback:{rating:number;comment:string|null}|null};
async function readResponse(response:Response){const body=await response.json();if(!response.ok)throw Error(body.details?.join('; ')||body.error||'Request failed');return body}
export default function GuestApp({roomId}:{roomId:string}){
 const [data,setData]=useState<Data|null>(null),[requests,setRequests]=useState<GuestRequest[]>([]),[view,setView]=useState('home'),[selected,setSelected]=useState<Service|null>(null),[qty,setQty]=useState(1),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[accessError,setAccessError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{try{const [d,r]=await Promise.all([fetch('/api/guest?roomId='+roomId,{cache:'no-store'}).then(readResponse),fetch('/api/requests?roomId='+roomId,{cache:'no-store'}).then(readResponse)]);setData(d);setRequests(r);setAccessError('')}catch(e){setAccessError((e as Error).message)}},[roomId]);
 useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},10000);return()=>clearInterval(timer)},[load]);
 if(!data)return <main className="container"><div className="card" style={{padding:24}}>{accessError?<><h1>Unable to open room</h1><p role="alert">{accessError}</p><button className="btn btn-primary" onClick={()=>void load()}>Try again</button></>:'Loading your room…'}</div></main>;
 const info=data.hotel.info;
 return <div className="guest-shell"><div className="guest-container"><header className="guest-head"><div className="guest-logo">{data.hotel.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</div><div>{data.hotel.name} • ROOM {data.room.number}</div><h1>Welcome to your stay.</h1><p>How can we help you today?</p></header>
 {accessError&&<p role="alert" className="notice">{accessError}</p>}{error&&<p role="alert" className="notice">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 {view==='home'&&<><div className="card hero-card"><span className="muted">Your room</span><h2>{data.room.number}</h2><span className="pill">{accessError?'Access unavailable':'Guest access active'}</span></div><div className="section-title"><h2>Quick access</h2></div><div className="service-grid">{[{v:'services',t:'Guest services',I:ClipboardList,d:'Towels, water & room care'},{v:'dining',t:'Dining',I:Utensils,d:'Menu & prices'},{v:'wifi',t:'Wi-Fi',I:Wifi,d:'Connect to the hotel network'},{v:'info',t:'Hotel information',I:Hotel,d:'Timings & facilities'}].map(({v,t,I,d})=><button className="card service-card" key={v} onClick={()=>setView(v)} style={{textAlign:'left'}}><I/><b>{t}</b><small>{d}</small></button>)}</div><div className="section-title"><h2>Your requests</h2></div><button className="btn btn-primary" onClick={()=>setView('requests')}>Track requests ({requests.length})</button>{info?.breakfastTime&&<div className="card" style={{padding:20,marginTop:20}}><b>Breakfast</b><p>{info.breakfastTime}</p></div>}</>}
 {view!=='home'&&<div className="section-title"><button className="btn btn-soft" onClick={()=>{setView('home');setSelected(null)}}>← Home</button><h2>{view==='requests'?'Your requests':view==='wifi'?'Wi-Fi':view==='info'?'Hotel information':view==='dining'?'Dining':'Guest services'}</h2></div>}
 {view==='services'&&<div className="grid">{!data.services.length&&<p className="card" style={{padding:20}}>No services available. Please contact reception.</p>}{data.services.map(s=><button className="card" style={{padding:20,textAlign:'left'}} key={s.id} disabled={!!accessError} onClick={()=>{setSelected(s);setQty(1);setNote('');setError('');setNotice('')}}><b>{s.name}</b><p className="muted">{s.description}</p><small>{s.estimatedMinutes} min estimated • {Number(s.price)>0?'₹'+s.price:'Complimentary'}</small></button>)}</div>}
 {selected&&<form className="card form" style={{padding:22,marginTop:18}} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/requests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({roomId,serviceId:selected.id,quantity:qty,note})}).then(readResponse);setNotice('Request #'+r.id.slice(-6).toUpperCase()+' received. You can track its status below.');setSelected(null);setView('requests');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><h2>{selected.name}</h2><label>Quantity<input type="number" min={1} max={20} required value={qty} onChange={e=>setQty(e.target.valueAsNumber)}/></label><label>Note for the team<textarea maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={busy||!!accessError} className="btn btn-primary">{busy?'Sending…':'Submit request'}</button><button type="button" disabled={busy} className="btn btn-soft" onClick={()=>setSelected(null)}>Cancel</button></form>}
 {view==='requests'&&<div className="grid"><p className="muted">Status refreshes every 10 seconds. Requests shown belong to this browser session.</p>{!requests.length&&<div className="card" style={{padding:20}}>No requests yet.</div>}{requests.map(r=><div className="card" style={{padding:20}} key={r.id}><span className={'status status-'+r.status.toLowerCase().replaceAll('_','-')}>{r.status.replaceAll('_',' ')}</span><h3>{r.service.name} × {r.quantity}</h3><small>#{r.id.slice(-6).toUpperCase()} • {new Date(r.createdAt).toLocaleString()}</small>{r.note&&<p>{r.note}</p>}{r.feedback?<p>Thank you for rating this service {r.feedback.rating}/5.</p>:r.status==='COMPLETED'&&<Feedback requestId={r.id} onSaved={load} disabled={!!accessError}/>}</div>)}</div>}
 {view==='dining'&&<div className="grid"><p className="card" style={{padding:18}}>For dining orders, contact reception or submit a Room Service request.</p>{!data.menu.length&&<p>No menu items available.</p>}{data.menu.map(m=><div key={m.id} className="card" style={{padding:20}}>{m.category&&<span className="pill">{m.category.name}</span>}<h3>{m.name}</h3><p>{m.description}</p><b>₹{m.price}</b></div>)}</div>}
 {view==='wifi'&&<div className="card" style={{padding:24}}><Wifi/><h2>{info?.wifiName||'Wi-Fi details not set'}</h2>{info?.wifiPassword?<><p>Password</p><strong style={{overflowWrap:'anywhere'}}>{info.wifiPassword}</strong><p><button className="btn btn-primary" onClick={async()=>{try{await navigator.clipboard.writeText(info.wifiPassword!);setNotice('Wi-Fi password copied')}catch{setNotice('Please select and copy the password shown above.')}}}>Copy password</button></p></>:<p>Please ask reception for Wi-Fi access.</p>}</div>}
 {view==='info'&&<div className="grid">{[['Address',data.hotel.address],['Breakfast',info?.breakfastTime],['Check-in',info?.checkinTime],['Check-out',info?.checkoutTime],['Facilities',info?.facilities],['Policies',info?.policies]].filter(([,v])=>v).map(([k,v])=><div key={k} className="card" style={{padding:20}}><b>{k}</b><p style={{whiteSpace:'pre-wrap'}}>{v}</p></div>)}{data.hotel.phone&&<a className="btn btn-primary" href={'tel:'+data.hotel.phone.replace(/[^+0-9]/g,'')}><Phone size={16}/> Call reception: {data.hotel.phone}</a>}</div>}
 <nav className="guest-bottom">{[{v:'home',t:'Home',I:Hotel},{v:'services',t:'Services',I:ClipboardList},{v:'dining',t:'Dining',I:Utensils},{v:'requests',t:'Requests',I:Clock}].map(({v,t,I})=><a key={v} href={'#'+v} onClick={e=>{e.preventDefault();setView(v);setSelected(null)}}><I size={18}/>{t}</a>)}</nav></div></div>
}
function Feedback({requestId,onSaved,disabled}:{requestId:string;onSaved:()=>Promise<void>;disabled:boolean}){const[rating,setRating]=useState(5),[comment,setComment]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');return <form className="form" style={{marginTop:20}} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await fetch('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({requestId,rating,comment})}).then(readResponse);await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Rate this service<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></label><label>Comment<textarea maxLength={1000} value={comment} onChange={e=>setComment(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy||disabled} className="btn btn-soft">{busy?'Saving…':'Send feedback'}</button></form>}
