'use client';
import {useState} from 'react';import {useRouter} from 'next/navigation';
export type Field={key:string;label:string;type?:'text'|'number'|'checkbox'|'password'|'textarea'|'email';options?:string[];required?:boolean};
type Row=Record<string,string|number|boolean|null>;
export default function Management({resource,title,fields,rows,defaults,canEdit=true,single=false}:{resource:string;title:string;fields:Field[];rows:Row[];defaults:Row;canEdit?:boolean;single?:boolean}){
 const router=useRouter(),[editing,setEditing]=useState<Row|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 return <div className="container"><h1>{title}</h1>{notice&&<p role="status" className="notice">{notice}</p>}{canEdit&&!single&&<button className="btn btn-primary" onClick={()=>{setEditing({...defaults});setError('')}}>Add new</button>}
 {editing&&<form className="card form" style={{padding:24,margin:'20px 0',maxWidth:650}} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/manage/'+resource,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(editing)});const b=await response.json();if(!response.ok)throw Error(b.details?.join('; ')||b.error);setEditing(null);setNotice('Saved successfully');router.refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>
 <h2>{editing.id?'Edit':'Add'} {title.toLowerCase()}</h2>{fields.map(f=><label key={f.key}>{f.label}{f.options?<select value={String(editing[f.key]??'')} onChange={e=>setEditing({...editing,[f.key]:e.target.value})}>{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==='checkbox'?<input type="checkbox" style={{width:'auto',marginLeft:12}} checked={Boolean(editing[f.key])} onChange={e=>setEditing({...editing,[f.key]:e.target.checked})}/>:f.type==='textarea'?<textarea value={String(editing[f.key]??'')} onChange={e=>setEditing({...editing,[f.key]:e.target.value})}/>:<input type={f.type||'text'} step={f.type==='number'?'any':undefined} required={f.required} autoComplete={f.type==='password'?'new-password':undefined} value={String(editing[f.key]??'')} onChange={e=>setEditing({...editing,[f.key]:f.type==='number'?e.target.valueAsNumber:e.target.value})}/> }</label>)}
 {error&&<p role="alert" className="notice">{error}</p>}<div><button disabled={busy} className="btn btn-primary">{busy?'Saving…':'Save'}</button> <button type="button" disabled={busy} className="btn btn-soft" onClick={()=>setEditing(null)}>Cancel</button></div></form>}
 <div className="grid" style={{gridTemplateColumns:'repeat(auto-fill,minmax(280px,1fr))',marginTop:22}}>{rows.map((row,i)=><div key={String(row.id||i)} className="card" style={{padding:22}}><h2>{String(row.name||row.roomNumber||title)}</h2>{fields.filter(f=>f.type!=='password').map(f=><p key={f.key}><b>{f.label}: </b>{typeof row[f.key]==='boolean'?(row[f.key]?'Yes':'No'):String(row[f.key]??'—')}</p>)}{canEdit&&<button className="btn btn-soft" onClick={()=>{const editable:Row={};for(const f of fields)editable[f.key]=f.type==='password'?'':row[f.key]??'';if(row.id)editable.id=row.id;setEditing(editable);setError('');setNotice('')}}>Edit</button>}
 {resource==='rooms'&&<div style={{display:'flex',gap:10,marginTop:12,flexWrap:'wrap'}}><a className="btn btn-primary" href={'/q/'+row.qrToken} target="_blank" rel="noreferrer">Open guest page</a><a className="btn btn-soft" href={'/api/qr/'+row.qrToken+'/image'} target="_blank" rel="noreferrer">QR image</a></div>}</div>)}</div>{!rows.length&&<p>No records yet.</p>}</div>
}
